NAME = "SHALOM OBINNA IS A GOOD MAN, HE LOVES CODING"
FIRST_NAME = "HE JOINS THE COMPANY OF HIS FRIENDS"
COMBINED_NAME = NAME + " [" + FIRST_NAME + "] " + " IS A CODER"
MSG = f" {NAME}  [{FIRST_NAME}]   IS A CODER "
print(MSG)
print(len(MSG))

